#spring:
  #datasource:
    #type: com.zaxxer.hikari.HikariDataSource
    #url: jdbc:postgresql://192.168.138.128:5432/killme
    #driver-class-name: org.postgresql.Driver
    #username: jack
    #password: tist24231451
    #maximum-pool-size: 10
  #jpa:
    #generate-ddl: true
    #show-sql: false
  #mail:
    #host: 192.168.1.2
    #port: 25
#tist:
  #admin:
    #debug: true
    #mail-from: online@tist.com.tw
    #upload: D:\upload