INSERT INTO clazz
VALUES ('101', '1');
INSERT INTO Student
VALUES ('0001', 'Anna', '101');
INSERT INTO Student
VALUES ('0002', 'Damnit', '101');
INSERT INTO Student
VALUES ('0003', 'Charlie', '101');
INSERT INTO Student
VALUES ('0004', 'Bob', '101');
INSERT INTO Student
VALUES ('0005', 'Electric', '101');

INSERT INTO USER_ROLE
VALUES (0, 'ADMIN'),
       (1, 'LEADER'),
       (2, 'NORMAL'),
       (99, 'BANNED');

INSERT INTO USER_DATA(NAME_, PASSWORD_, ACTIVATE_, GENDER_, USER_ROLE_ID_)
VALUES ('admin', 'admin', TRUE, 'admin', 0);
INSERT INTO USER_DATA(NAME_, PASSWORD_, ACTIVATE_, GENDER_, USER_ROLE_ID_)
VALUES ('Alice', 'abc123', TRUE, 'Female', 1);
INSERT INTO USER_DATA(NAME_, PASSWORD_, ACTIVATE_, GENDER_, USER_ROLE_ID_)
VALUES ('Alex', 'aaaa123', TRUE, 'Male', 2);
INSERT INTO USER_DATA(NAME_, PASSWORD_, ACTIVATE_, GENDER_, USER_ROLE_ID_)
VALUES ('Peter', 'H31l0w0rld', FALSE, 'Male', 99);
INSERT INTO USER_DATA(NAME_, PASSWORD_, ACTIVATE_, GENDER_, USER_ROLE_ID_)
VALUES ('Daisy', 'thisIsABook', FALSE, 'Female', 99);
INSERT INTO USER_DATA(NAME_, PASSWORD_, ACTIVATE_, GENDER_, USER_ROLE_ID_)
VALUES ('Jessie', 'ppap5566', TRUE, 'Male', 2);
